### ISSUE TITLE
[Bug 🐛] Link to event-driven.io blog is broken in "My knowledge resources" section

### ISSUE THREAD

**Issue by Mehdi-H** [szymon6927/szymonmiks.pl#1]
Hello @szymon6927 ,

Firstly, thank you for sharing your content, I just discovered your blog in a newsletter and there is a lot of interesting things :)

I just found out that a link in your ["My knowledge resources"](https://github.com/szymon6927/szymonmiks.pl/blob/master/blog/content/page/04-my-knowledge-sources/index.md?plain=1#L32) section is broken.

* <https://event-driven.io/en/s> leads to [HTTP 404](https://event-driven.io/en/404.html)

## Suggestion

* The link can be replaced with <https://event-driven.io/> or <https://event-driven.io/en>

**Comment by szymon6927** [comment]
Hi, thank you so much! I have fixed it. The link is working now!
